### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by rmwu** [rpatrik96/nl-causal-representations#10]
Hi! Thanks for the cool paper :) Do you have any recommendations on the easiest way to run your code on a custom dataset, say an N x D array of observations? Thank you!

**Comment by rpatrik96** [comment]
Hi @rmwu! Thanks for your comment. 
1. If the data comes from a contrastive data generation process (i.e., paired observations of positive and negative samples), then you need to rewrite our dataset to provide the `(anchor, pos_pair, neg_pairs)`.
2. If your data is not paired as described above, then you will need an algorithm that is identifiable and for which your dataset satisfies the assumptions (e.g., if you have non-stationary time series data, you might use TCL from [this repo](https://github.com/hmorioka/IIA) ), then calculate the Jacobian.
3. If neither is viable, then there is not much to do, unfortunately. (You might train an overparametrized model then calculate its Jacobian with [this function](https://github.com/rpatrik96/nl-causal-representations/blob/master/care_nl_ica/dep_mat.py#LL7C8-L7C8), but there are no guarantees for that).

**Comment by rmwu** [comment]
Hi! Thanks for the update and the references! :) I ended up doing something similar to the first option, which seemed to work. Have a nice day!
